### ISSUE TITLE
Shogun is 3-clause BSD

### ISSUE THREAD

**Issue by jamiebullock** [bennylp/awesome-cpp-ml#1]
Thanks for this fantastic and useful resource.

I think there is one error, Shogun seems to be 3-clause BSD. Not sure if it changed at some point:

https://github.com/shogun-toolbox/shogun/blob/develop/LICENSE

**Comment by bennylp** [comment]
Thanks for reaching out, Jamie. You're right, Shogun has finally moved to
BSD (it was GPL at the time). I've updated the table. Thanks again.
